### ISSUE TITLE
运行后只能输出一个节点

### ISSUE THREAD

**Issue by zhouceo** [Telly-S/Tint-XML#1]
你好 ，为什么运行后只有一个节点？最后的运行结果为
type = shapeOne
type = shapeTwo
parentShape's child is points, has 1 nodes
451 33 495 0 
后面的节点不显示了，也就是说parentShape->children.nodeSize为1

**Comment by Telly-S** [comment]
你好，是可以输出两个节点的。只不过我只打印了一个。`shapes->nodeSize` 是shape节点的个数，在图中是有两个的。`XMLNode* parentShape = XMLNodeList_at(shapes, 0);` 这里的0只是最前面的一个，`parentShape`就是获取的shape 0的实例对象，改为1就是第二个。
而你说的 `parentShape->children.nodeSize`为1指的是shape的子节点也就是points的个数为1个。

**Comment by zhouceo** [comment]
就是<shape>的子节点<points>，根据你的xml文件来看，现在把
`XMLNode *parentShape = XMLNodeList_at(shapes, 0);`改为
`XMLNode *parentShape = XMLNodeList_at(shapes, 1);`
就可以输出123 45 678 90了  但是第一个子节点的数据就没了，不能一下输出全部吗？像这种
```
type = shapeOne
type = shapeTwo
parentShape's child is points, has 1 nodes
451 33 495 0
123 45 678 90
```

**Comment by zhouceo** [comment]
就是<shape>的子节点<points>，根据你的xml文件来看，现在把
`XMLNode *parentShape = XMLNodeList_at(shapes, 0);`改为
`XMLNode *parentShape = XMLNodeList_at(shapes, 1);`
就可以输出123 45 678 90了  但是第一个子节点的数据就没了，不能一下输出全部吗？像这种
```
type = shapeOne
type = shapeTwo
parentShape's child is points, has 2 nodes
451 33 495 0
123 45 678 90
```

**Comment by Telly-S** [comment]
> 就是的子节点，根据你的xml文件来看，现在把 `XMLNode *parentShape = XMLNodeList_at(shapes, 0);`改为 `XMLNode *parentShape = XMLNodeList_at(shapes, 1);` 就可以输出123 45 678 90了 但是第一个子节点的数据就没了，不能一下输出全部吗？像这种
> 
> ```
> type = shapeOne
> type = shapeTwo
> parentShape's child is points, has 2 nodes
> 451 33 495 0
> 123 45 678 90
> ```

当然可以，你放到循环了就行了。shapes->nodeSize 是shape节点的个数，在这里是2，有了这个数据，你搞个循环就行了。还有 parentShape's child is points, has 1 nodes 这句话的意思不是 shape有1个，而是shape下面的子节点也就是 points 有一个。

**Comment by zhouceo** [comment]
好了 谢谢，还有个问题，我想使用你这个xml的解析函数用在stm32里面，现在我想使用的功能是需要将我的数据类型，变量名，参数数据使用xml格式保存到一个文件中，然后通过串口发给单片机，然后单片机在使用你这个解析函数来解析，可以吗？

**Comment by Telly-S** [comment]
> 好了 谢谢，还有个问题，我想使用你这个xml的解析函数用在stm32里面，现在我想使用的功能是需要将我的数据类型，变量名，参数数据使用xml格式保存到一个文件中，然后通过串口发给单片机，然后单片机在使用你这个解析函数来解析，可以吗？

也可以，不过你要修改一下 `XMLDocument_load()` 函数，把其中的 `docBuffer` 指向你串口接收的缓冲区。

**Comment by zhouceo** [comment]
奥奥，那就是直接把路径参数去掉，然后也不用打开文件了，直接将docBuffer指向我的串口缓冲区就行了，对吧

**Comment by Telly-S** [comment]
是的

**Comment by zhouceo** [comment]
好的  感谢

**Comment by zhouceo** [comment]
你好，遇到一个问题，就是我将你的代码移植到stm32中后，发送你的xml文件，能够正常解析，发送我自己写的xml文件，就会跳到函数`XMLDocument_load()`的`printf("Error: \"%s\" at line %d in %s\r\n", "Text outside of document", __LINE__, __FILE__);`这句话里面，然后就return了，这是什么情况？
自己写的xml文件为：
`<?xml version="1.0" encoding="UTF-8" ?>
<annotation>
	
	<CreateVersion>1.0</CreateVersion>
	<folder></folder>
	<shape type="double">
		<points>
			<x>K</x>
			<y>33.56</y>
		</points>
	</shape>
	<shape type="int32">
		<points>
			<x>zero</x>
			<y>45</y>
		</points>
	</shape>
	<shape type="DN_TypeDef">
		<points>
			<x>DN</x>
			<y>45</y>
		</points>
	</shape>
	<shape type="char">
		<points>
			<x>sn[SN_SIZE]</x>
			<y>qwe</y>
		</points>
	</shape>
	<shape type="VUnit_TypeDef">
		<points>
			<x>rateUnit</x>
			<y>25.25</y>
		</points>
	</shape>
	.........
        .........
        .........
</annotation>`

**Comment by zhouceo** [comment]
你好，遇到一个问题，就是我将你的代码移植到stm32中后，发送你的xml文件，能够正常解析，发送我自己写的xml文件，就会跳到函数`XMLDocument_load()`的`printf("Error:` \"%s\" at line %d in %s\r\n", "Text outside of document", __LINE__, __FILE__)`;这句话里面，然后就return了，这是什么情况？
自己写的xml文件为：
![Uploading 微信图片_20240625084158.png…]()

**Comment by zhouceo** [comment]
你好，遇到一个问题，我将你的代码移植到stm32中后，发送你的xml文件能够正常的解析，发送自己修改的xml文件后，就会跳到函数`XMLDocument_load()`中的`printf("Error: \"%s\" at line %d in %s\r\n", "Text outside of document", __LINE__, __FILE__);`这句话，然后就return了，这是什么问题呢？我的xml文件为：
[test1.txt](https://github.com/user-attachments/files/15962931/test1.txt)

**Comment by zhouceo** [comment]
> 你好，遇到一个问题，我将你的代码移植到stm32中后，发送你的xml文件能够正常的解析，发送自己修改的xml文件后，就会跳到函数中的这句话，然后就return了，这是什么问题呢？我的xml文件为： [test1.txt](https://github.com/user-attachments/files/15962931/test1.txt)`XMLDocument_load()``printf("Error: \"%s\" at line %d in %s\r\n", "Text outside of document", __LINE__, __FILE__);`

没有移植的时候能够解析出来，移植后就只能解析出你的xml了

**Comment by Telly-S** [comment]
> Reference

你的意思是在电脑上可以解析出来你的数据，但是在stm32上就不行吗

**Comment by zhouceo** [comment]
> > 参考
> 
> 你的意思是在电脑上可以解析出来你的数据，但是在stm32上就不行吗

对，目前是把堆栈空间调大了，现在还行

**Comment by zhouceo** [comment]
> > Reference
> 
> 你的意思是在电脑上可以解析出来你的数据，但是在stm32上就不行吗

你好  代码是不是有些地方堆或者栈没有释放啊？xml文件只有5k，stm32上堆设置了60k还是会进入hardfault，程序运行到函数XMLDocument_load()的最后return TRUE，然后下一步直接就进入了hardfault
